name: Run Snowflake Script

on:
  push:
    branches:
      - main

jobs:
  run-snowflake:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SF_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
      SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SF_SCHEMA }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Snowflake CLI
      run: |
        pip install --upgrade pip
        pip install snowflake-cli-labs

    - name: Run SQL Script in Snowflake
      run: |
        snow sql -f 02_insert_data/insert_customer.sql
