name: Run SQL with Snow CLI

on:
  push:
    branches: [main]

jobs:
  snowflake-job:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Install Snow CLI
        run: |
          pip install --upgrade pip
          pip install snowflake-cli-labs

      - name: ✅ Run SQL using inline credentials
        env:
          SNOWFLAKE_ACCOUNT: pipbfcf-xr87735
          SNOWFLAKE_USER: mithrakarthik2025
          SNOWFLAKE_PASSWORD: Mithrakarthik2025NEW
          SNOWFLAKE_ROLE: ACCOUNTADMIN
          SNOWFLAKE_WAREHOUSE: COMPUTE_WH
          SNOWFLAKE_DATABASE: SNOWPARKDB
          SNOWFLAKE_SCHEMA: SNOWPARKSCHEMA
        run: |
          snow sql -f 02_insert_data/insert_customer.sql
