name: Run Snowflake Script using snowsql

on:
  push:
    branches:
      - main

jobs:
  run-snowsql:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout Code
      uses: actions/checkout@v3

    - name: ✅ Install snowsql CLI from Snowflake CDN
      run: |
        mkdir -p $HOME/snowsql
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
        bash snowsql-1.2.21-linux_x86_64.bash -- -y -d $HOME/snowsql
        echo "$HOME/snowsql/bin" >> $GITHUB_PATH
        chmod +x $HOME/snowsql/bin/snowsql

    - name: ✅ Verify snowsql is installed
      run: |
        echo "PATH = $PATH"
        which snowsql || true
        snowsql -v || echo "snowsql not available"

    - name: ✅ Run SQL Script using inline credentials
      run: |
        snowsql \
          -a pipbfcf-xr87735 \
          -u mithrakarthik2025 \
          -p Mithrakarthik2025NEW \
          -r ACCOUNTADMIN \
          -w COMPUTE_WH \
          -d SNOWPARKDB \
          -s SNOWPARKSCHEMA \
          -f 02_insert_data/insert_customer.sql
