name: Run SQL with Snow CLI

on:
  push:
    branches: [main]  # or update with your branch name

jobs:
  run-snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Install SnowSQL CLI via pip
        run: |
          pip install --upgrade pip
          pip install snowflake-cli-labs

      - name: ✅ Run SQL script using inline credentials
        run: |
          snow sql \
            --account pipbfcf-xr87735 \
            --username mithrakarthik2025 \
            --password Mithrakarthik2025NEW \
            --role ACCOUNTADMIN \
            --warehouse COMPUTE_WH \
            --database SNOWPARKDB \
            --schema SNOWPARKSCHEMA \
            -f 02_insert_data/insert_customer.sql
