name: Run Snowflake Script using pip SnowSQL

on:
  push:
    branches:
      - main

jobs:
  run-snowsql:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: pipbfcf-xr87735
      SNOWFLAKE_USER: mithrakarthik2025
      SNOWFLAKE_PASSWORD: Mithrakarthik2025NEW
      SNOWFLAKE_ROLE: ACCOUNTADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_DATABASE: SNOWPARKDB
      SNOWFLAKE_SCHEMA: SNOWPARKSCHEMA

    steps:
    - name: ✅ Checkout Code
      uses: actions/checkout@v3

    - name: ✅ Install SnowSQL CLI via pip
      run: |
        python3 -m pip install --upgrade pip
        pip install snowflake-cli-labs

    - name: ✅ Run SQL Script
      run: |
        snow sql -f 02_insert_data/insert_customer.sql
