name: Run Snowflake Script

on:
  push:
    branches:
      - main

jobs:
  run-snowflake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Snowflake CLI
      run: |
        python3 -m pip install --upgrade pip
        pip install snowflake-cli-labs

    - name: Configure Snowflake Connection
      run: |
        snow connection add default \
          --account-name ${{ secrets.SF_ACCOUNT }} \
          --username ${{ secrets.SF_USER }} \
          --password ${{ secrets.SF_PASSWORD }} \
          --role-name ${{ secrets.SF_ROLE }} \
          --warehouse-name ${{ secrets.SF_WAREHOUSE }} \
          --database-name ${{ secrets.SF_DATABASE }} \
          --schema-name ${{ secrets.SF_SCHEMA }}

    - name: Run SQL Script in Snowflake
      run: |
        snow sql -f 02_insert_data/insert_customer.sql
