name: Run Snowflake Script using pip SnowSQL

on:
  push:
    branches:
      - main

jobs:
  run-snowsql:
    runs-on: ubuntu-latest

    steps:
    - name: ✅ Checkout Code
      uses: actions/checkout@v3

    - name: ✅ Install SnowSQL CLI via pip
      run: |
        python3 -m pip install --upgrade pip
        pip install snowflake-cli-labs

    - name: ✅ Configure Snowflake Connection
      run: |
        snow connection add --connection-name devconn \
          --account pipbfcf-xr87735 \
          --user mithrakarthik2025 \
          --password Mithrakarthik2025NEW \
          --role ACCOUNTADMIN \
          --warehouse COMPUTE_WH \
          --database SNOWPARKDB \
          --schema SNOWPARKSCHEMA

    - name: ✅ Run SQL Script
      run: |
        snow sql -f 02_insert_data/insert_customer.sql --connection devconn
