name: Run Snowflake SQL via Snow CLI

on:
  push:
    branches: [main]

jobs:
  run-snowflake:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: pipbfcf-xr87735
      SNOWFLAKE_USER: mithrakarthik2025
      SNOWFLAKE_PASSWORD: Mithrakarthik2025NEW
      SNOWFLAKE_ROLE: ACCOUNTADMIN
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_DATABASE: SNOWPARKDB
      SNOWFLAKE_SCHEMA: SNOWPARKSCHEMA

    steps:
      - name: ✅ Checkout Code
        uses: actions/checkout@v3

      - name: ✅ Install Snow CLI
        run: |
          pip install --upgrade pip
          pip install snowflake-cli-labs

      - name: ✅ Run SQL Script using Snow CLI
        run: |
          snow sql -f 02_insert_data/insert_customer.sql
